apps:
  # List of 3rd party apt repos to add.
  repos:
    docker-ce:
      url: https://download.docker.com/linux/fedora/docker-ce.repo

    vscode:
      gpg: https://packages.microsoft.com/keys/microsoft.asc
      repo: |
        [code]
        name=Visual Studio Code
        gpgkey=https://packages.microsoft.com/keys/microsoft.asc
        baseurl=https://packages.microsoft.com/yumrepos/vscode
        enabled=1
        gpgcheck=1

  # List of dnf packages to install.
  dnf:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    - https://downloads.slack-edge.com/linux_releases/slack-4.14.0-0.1.fc21.x86_64.rpm
    - https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
    - https://zoom.us/client/latest/zoom_x86_64.rpm

    - '@development-tools' # Build-essentials analog.
    - golang

    - exfat-utils # Utilities to create, check, label and dump exFAT file system 
    - grub-customizer # GUI for GRUB settings management
    - htop # Terminal system monitor
    - java-latest-openjdk # Jave development kit
    - jq # Takes JSON input and retrieves data by query
    - mc # Two panel terminal file manager
    - neofetch # Shows Linux System Information with Distribution Logo
    - net-tools # Base network tools
    - stacer # Cool CleanMyMac alternative

    - arj # arj archiver
    - lha # lzh unarchiver
    - unrar # rar unarchiver

    - libreoffice
    - libreoffice-langpack-uk
    - libreoffice-langpack-ru
    - libreoffice-help-uk
    - libreoffice-help-ru

    - dia
    - evolution
    - evolution-ews
    - flameshot
    - inkscape
    - transmission
    - telegram-desktop
    - vlc

    ### Fonts
    - dejavu-fonts-all
    - google-roboto-condensed-fonts
    - google-roboto-fonts
    - google-roboto-mono-fonts
    - google-roboto-slab-fonts
    - jetbrains-mono-fonts-all
    - open-sans-fonts
    - sorkintype-merriweather-fonts
    - sorkintype-merriweather-sans-fonts
    - typetogether-literata-fonts
    - https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm # Microsoft Fonts

  flatpak:
    - com.getpostman.Postman # API debugging tool
    - com.github.johnfactotum.Foliate # eBook reader
    # - com.discordapp.Discord
    # - com.rafaelmardojai.Blanket # Listen to different sounds
    # - com.spotify.Client

docker:
  install: yes
  docksal:
    install: yes
    settings:
      DOCKSAL_CONTAINER_HEALTHCHECK_INTERVAL: 1m # Throttle healthchecks for less syslog entries.
      DOCKSAL_DNS_DISABLED: 0 # Set 1 for disable docksal DNS container at all.
      DOCKSAL_DNS_UPSTREAM: 1.1.1.1 # Use CloudFlare DNS as its faster than google's DNS.

php:
  install: yes
  # @TODO: Add composer version select: v1 or v2.
  composer:
    # List of global composer packages to install.
    #
    # NOTE: All the following packages will be installed using `consolidation/cgr`.
    global:
      - drush/drush
      - squizlabs/php_codesniffer
      - drupal/coder              # PHPCS Drupal standards
      - friendsofphp/php-cs-fixer # PHPCS standard fixer
      - mglaman/drupal-check      # Drupal static code analysis tool

node:
  install: yes
  # List of node versions to install.
  versions: 
    - 14
    - 12
    - 10
  defaultVersion: node # Latest installed node version.
  npm:
    # List of global npm packages to install for default node.
    global: 
      - bower
      - eslint
      - eslint-config-airbnb
      - eslint-config-google
      - eslint-config-standard
      - eslint-plugin-import
      - eslint-plugin-jsx-a11y
      - eslint-plugin-node
      - eslint-plugin-promise
      - eslint-plugin-react
      - eslint-plugin-react-hooks
      - firebase-tools
      - flow
      - flow-bin
      - gulp
      - http-server
      - lsp
      - typescript
      - vscode-css-languageserver-bin
      - vscode-html-languageserver-bin
      - yarn

python:
  install: yes
  pip3:
    # List of global packages to install.
    global:
      - awscli # AWS cli.
      - ffmpeg-normalize # Normalizes audio using ffmpeg.
      - yq # Takes YAML input and retrieves data by query.

vscode:
  install: yes
  # List of plugins to install.
  extensions:
    - acarreiro.calculate                # Calculates inline math expr
    - christian-kohler.path-intellisense # File path autocomplete
    - coenraads.bracket-pair-colorizer   # Bracket Pair Colorizer
    - dakara.transformer                 # Filter, Sort, Unique, Reverse, Align, CSV, Line Selection, Text Transformations and Macros
    - editorconfig.editorconfig          # EditorConfig support
    - esbenp.prettier-vscode             # Prettier - Code formatter
    - github.github-vscode-theme         # GitHub color theme
    - golang.go                          # Golang support
    - hookyqr.beautify                   # HTML/JSON beautifier
    - mhutchie.git-graph                 # Git graph
    - mikestead.dotenv                   # .env support
    - ms-azuretools.vscode-docker        # Docker support
    - ms-python.python                   # Python support
    - pkief.material-icon-theme          # Material Icon Theme
    - TabNine.tabnine-vscode             # AI-assisted autocomplete
    - tyriar.lorem-ipsum                 # Lorem Ipsum generator
    - william-voyek.vscode-nginx         # nginx.conf support
    - yzhang.markdown-all-in-one         # Markdown tools
    #- alefragnani.Bookmarks             # Bookmarks

    # Node/NPM/Yarn specific extensions
    - christian-kohler.npm-intellisense # NPM better autocomplete
    - dbaeumer.vscode-eslint            # Eslint support
    - mariusschulz.yarn-lock-syntax     # yarn.lock syntax highlight

    # PHP/Drupal specific extensions
    - bbeversdorf.drupal-check # Drupal: check for deprecations
    - ikappas.composer         # Composer support
    - ikappas.phpcs            # PHP CodeSniffer

jetbrains:
  toolbox:
    install: yes
